### ISSUE TITLE
Create keys and certs

### ISSUE THREAD

**Issue by drts01** [CMeza99/k8s-config#1]
create ca, keys, certs in `/etc/kubernetes/pki/`

    apiserver.crt
    apiserver.key
    apiserver-kubelet-client.crt
    apiserver-kubelet-client.key
    ca.crt
    ca.key
    front-proxy-ca.crt
    front-proxy-ca.key
    front-proxy-client.crt
    front-proxy-client.key
    sa.key
    sa.pub

and update config files,
i.e. `/etc/kubernetes/admin.conf`
```yaml
apiVersion: v1
clusters:
- cluster:
    # certificate-authority-data:
    server: https://<api_ip>:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    # client-certificate-data:
    # client-key-data:
```
